export enum ReplacementStatus {
  CREATED = 'CREATED', // CREADO
  PENDING = 'PENDING', // PENDIENTE
  IN_PROGRESS = 'IN_PROGRESS', // EN PROCESO
  COMPLETED = 'COMPLETED', // FINALIZADO
  LOADED_IN_HURACAN = 'LOADED_IN_HURACAN', // CARGADO EN HURACAN
}
