export enum TicketAction {
  CREATED = 'TICKET_CREATED',
  ASSIGNED = 'ASSIGNED_TO_TECHNICIAN',
  RESOLVED = 'ISSUE_RESOLVED',
  REOPENED = 'TICKET_REOPENED',
  CLOSED = 'TICKET_CLOSED',
  COMMENT_ADDED = 'COMMENT_ADDED',
}
