export enum TicketAction {
  CREATED = 'CREATED',
  ONPROGRESS = 'ONPROGRESS',
  ASSIGNED = 'ASSIGNED',
  RESOLVED = 'RESOLVED',
  REOPENED = 'REOPENED',
  CLOSED = 'CLOSED',
  COMMENT_ADDED = 'COMMENT_ADDED',
}
