export enum TicketStatus {
  SIN_ASIGNAR = 'SIN_ASIGNAR',
  PENDING_CLOSE = 'PENDING_CLOSE',
  ASIGNADO = 'ASIGNADO',
  EN_PROCESO = 'EN_PROCESO',
  EN_ESPERA = 'EN_ESPERA',
  RESUELTO = 'RESUELTO',
  CANCELADO = 'CANCELADO',
  TRAVEL = 'TRAVEL',
  IN_REMOTE = 'IN_REMOTE',
  ON_SITE = 'ON_SITE',
  SUPPORT_REQUEST = 'SUPPORT_REQUEST'
}
