export enum SolicitudEtapa {
  SOLICITUD = 'SOLICITUD',
  AUTORIZACION_SERVICIO = 'AUTORIZACION_SERVICIO',
  ASIGNACION_TECNICO = 'ASIGNACION_TECNICO',
  LOGISTICA = 'LOGISTICA',
  MENSAJERIA = 'MENSAJERIA',
  COMPRA_REFACCION = 'COMPRA_REFACCION',
  FINALIZADA = 'FINALIZADA',
}
